version: '3'
services:
    db:
        container_name: db_list
        image: mysql:5.7
        restart: always
        ports:
            - "3309:3306"
        env_file:
            - .env
    list:
        container_name: app_list
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - ".:/list"
        ports:
            - "3001:3000"
        depends_on:
            - db
        links:
            - db
        env_file:
            - .env
