name: CI

on:
  push:
    branches:
      - '**'

env:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_ROOT_HOST: 172.18.0.1
  MYSQL_LOG_CONSOLE: true
  MYSQL_PASSWORD: password
  MYSQL_ROOT_USER: root
  WEATHER_API_KEY: 2ef56a4cf9b6a2f3ac00b249e0c861d34a507e246e5b2d73a0c39bd7ad7f1d9e
  LATITUDE: 53.8930
  LONGITUDE: 27.5674

jobs:
  Rubocop:
    runs-on: ubuntu-20.04
    steps:
      - name: Workflow access
        uses: actions/checkout@v3

      - name: Build app
        uses: ./.github/actions/build

      - name: Run Rubocop
        continue-on-error: true
        run: bundle exec rubocop

  RSpec:
    runs-on: ubuntu-20.04
    services:
      mysql:
          image: mysql
          env:
            MYSQL_ROOT_PASSWORD: password
          ports:
            - 8888:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Workflow access
        uses: actions/checkout@v3

      - name: Build app
        uses: ./.github/actions/build

      - name: Build and test with rspec
        run: |
          sudo /etc/init.d/mysql start  --skip-grant-tables
          bundle exec rails db:create db:migrate RAILS_ENV=test
          bin/rails assets:precompile
          rspec spec

  Code-coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Workflow access
        uses: actions/checkout@v3

      - name: Build app
        uses: ./.github/actions/build

      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: ./coverage
